# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Jihwan Moon
description: Security Researcher & Developer
url: https://up2moon.github.io
baseurl: /

paginate: 5

# Custom vars
version: 2.1.0

github: https://github.com/up2moon
